### ISSUE TITLE
System.IO.DirectoryNotFoundException

### ISSUE THREAD

**Issue by zoltanhalasz** [oqtane/DNF.Projects#2]
When I try to run the DNF projects, this is what I get (after hitting F5 in the Server Project of DNF.Projects).
Am I missing something?
System.IO.DirectoryNotFoundException: 'C:\Dotnet\DNF.Projects\Client\bin\Debug\netstandard2.1\wwwroot\'

**Comment by sbwalker** [comment]
You do not run the Module solution directly. You build the Module solution and it copies the DLLs to the Oqtane framework /bin folder. Then you run Oqtane and it dynamically loads the Module.

**Comment by zoltanhalasz** [comment]
Yes, I see that in the documentation. I did watch the videos but still doesn't work. After building DNF.Projects (which is in the same folder as Octane.Framework), the files are not copied to  C:\Dotnet\oqtane.framework\Oqtane.Shared\bin\Debug
The reason could be that for the Octane.Framework we have .Net 5.0 and DNF.Projects, we have .Net Core 3.1? Should we update it also to .Net 5.0?
