### ISSUE TITLE
Update Wix Toolset repo

### ISSUE THREAD

**Issue by rseanhall** [oqtane/DNF.Projects#4]
Sorry if this is not the right place to request this. On https://www.dnfprojects.com, The WiX Toolset repo is currently set to https://github.com/wixtoolset/Core, which was one of many micro repos that got consolidated back to a mono-repo last year. The active repo is https://github.com/wixtoolset/wix4, so it would be great if the website could be updated to use that repo instead. Thanks.

**Comment by sbwalker** [comment]
Apologies, I just noticed this issue now. The Url has now been updated.
