### ISSUE TITLE
No graphic is shown

### ISSUE THREAD

**Issue by jaruiz-ual** [oqtane/DNF.Projects#5]
Directory of the module is at the same level than oqtane.framework.
After installing the module in one page I have added several github projects urls.
I have checked that the data  are in the database, but no graphics are shown in the page.

**Comment by jaruiz-ual** [comment]
I do not know why, but in the last try it seems that it is working.

**Comment by jaruiz-ual** [comment]
I can see some empty data, but nothing else. It is not working as expected.

**Comment by jaruiz-ual** [comment]
line 50 of ProjectRepositoty.cs in the Repository folder in DNF.Projects.Server 
the method
public IEnumerable<ProjectActivity> GetProjectActivity(int ProjectId, DateTime FromDate, DateTime ToDate) 

is called with date parameters  in the format mm/dd/yyyy   but my local date format is dd/mm/yyyy  then no ProjectActivity is found.

**Comment by sbwalker** [comment]
Sounds like there is an internationalization bug in the module

**Comment by jaruiz-ual** [comment]
Hi Shaun,As I did not know why any data of GitHub project is loaded by the module  then I filled manually them.  And I noticed that even in this way, any record was not selected to be shown (the filter between dates is not working in my case).Then, surfing around de source code, I  realiced  that it is necessary to fill in the Project Settings tab (GithubToken) in order to Access to the Github api for project data (start, contributions …). And also it is necessary activate the Scheluled job for the Github Projects. But I do not know where I can found the information to  access to those data using the Github api, for checking if the module work as expected.So, what information I have to set in the textboxs of the Project Settings Tab:GithubToken, NotifyName and NotityEmail?Thank you in advance. Enviado desde Correo para Windows De: Shaun WalkerEnviado: lunes, 28 de noviembre de 2022 19:05Para: oqtane/DNF.ProjectsCC: jaruiz-ual; State changeAsunto: Re: [oqtane/DNF.Projects] No graphic is shown (Issue #5) Sounds like there is an internationalization bug in the module—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you modified the open/close state.Message ID: ***@***.***> Libre de virus.www.avg.com

**Comment by sbwalker** [comment]
Are you interested in this project as an example of how to create an Oqtane module (ie. including a schedule job and JavaScript interop)... or are you interested in capturing daily metrics from Github?

**Comment by sbwalker** [comment]
Like most real world applications this module has a number of dependencies which need to be configured correctly in order for the full functionality to be enabled. You would specify these in the Module Settings:

1. You need to create your own Github Token: https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token and enter the value.

2. You should specify the Notify Name as your name and Notify Email as your preferred email address. These would be used to notify you if there was an issue accessing the Github API. However for this to work correctly, you would need to ensure the Notification job is also enabled in your installation and the SMTP Settings are set properly in the Site Settings..

**Comment by jaruiz-ual** [comment]
Thank you very much. Enviado desde Correo para Windows De: Shaun WalkerEnviado: lunes, 28 de noviembre de 2022 22:20Para: oqtane/DNF.ProjectsCC: jaruiz-ual; State changeAsunto: Re: [oqtane/DNF.Projects] No graphic is shown (Issue #5) Like most real world applications this module has a number of dependencies which need to be configured correctly in order for the full functionality to be enabled. You would specify these in the Module Settings:You need to create your own Github Token: https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token and enter the value.You should specify the Notify Name as your name and Notify Email as your preferred email address. These would be used to notify you if there was an issue accessing the Github API. However for this to work correctly, you would need to ensure the Notification job is also enabled in your installation and the SMTP Settings are set properly in the Site Settings..—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you modified the open/close state.Message ID: ***@***.***> Libre de virus.www.avg.com

**Comment by jaruiz-ual** [comment]
Finally I got the module working properly with some tricks. 
1) Create a user key to be able to access the github apis (as you pointed).
2) Fill in the configuration of the module using that key. 
3) Enable the module update frequency in "Scheduled Jobs" in the administration panel.
4) Add urls of the existing Github projects in the module, but be careful that you have to access the projects type combobox and change it (you cannot leave the default value "communtity", because it does not store anything – it seems to be a bug).

What was happend
The Visual studio debugger always displays the value of a date field in the format "mm/dd/yyyy" when the mouse is on it. That's why I thought there was a problem in the format of the input parameters of the date type in the method that selected the git projects, but the problem was not there, it was in the "project type" combobox that was left with the default value " community" without changing it, the value null is entered in the database record, and therefore no records are selected.

**Comment by jaruiz-ual** [comment]
There is another bug in the view.razor source code. When a project is displayed all data are shown. It is necessary a where clausulae filtering the project id (in the line 123, inside the Display() method).
![image](https://user-images.githubusercontent.com/62284884/205254883-d6db411f-8781-4cc4-95b2-c2e0b8d033c7.png).

**Comment by jaruiz-ual** [comment]
when the interop.CreateChart is called (line 175 of View.razor)  the fontColor options is set to "white". Then if the background of the module is also "white"  the labels of the projects in the graph can not be seen. At least the fontColor property of the labels should be configurable in the module (or set to another colour distinct of the background colour dinamically)

**Comment by sbwalker** [comment]
@jaruiz-ual I have to apologize... I finally had time to open the project locally and I noticed that I have a bunch of code files that were modified but not submitted to the repo. I will address get this fixed this weekend.

**Comment by sbwalker** [comment]
@jaruiz-ual this commit should resolve all of your issues:

https://github.com/oqtane/DNF.Projects/commit/7d7b151cd09ee33bb512722b96ec08d99a019663

**Comment by jaruiz-ual** [comment]
Thank you very much!! Enviado desde Correo para Windows De: Shaun WalkerEnviado: lunes, 12 de diciembre de 2022 15:23Para: oqtane/DNF.ProjectsCC: jaruiz-ual; MentionAsunto: Re: [oqtane/DNF.Projects] No graphic is shown (Issue ***@***.*** this commit should resolve all of your issues:7d7b151—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by jaruiz-ual** [comment]
Hi Shaun,I have updated the source code of DNF.Projects.However, there is a problem with the field category when adding a Project.  The select tag does not change the value of the binded variable. It is always null.And I do not know why .  Enviado desde Correo para Windows De: Jose Andres Moreno RuizEnviado: lunes, 12 de diciembre de 2022 21:50Para: oqtane/DNF.ProjectsAsunto: RE: [oqtane/DNF.Projects] No graphic is shown (Issue #5) Thank you very much!! Enviado desde Correo para Windows De: Shaun WalkerEnviado: lunes, 12 de diciembre de 2022 15:23Para: oqtane/DNF.ProjectsCC: jaruiz-ual; MentionAsunto: Re: [oqtane/DNF.Projects] No graphic is shown (Issue ***@***.*** this commit should resolve all of your issues:7d7b151—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by sbwalker** [comment]
I will take a look today.
