### ISSUE TITLE
Bug: Project Information Modal Not Displaying Project Details with a Lost Return Url Alias

### ISSUE THREAD

**Issue by thabaum** [oqtane/DNF.Projects#8]
# Issue

## Description
Project Information Modal Not Displaying Project Details with a Lost Return Url Alias

## Steps to Reproduce

1. Click on a project in the dnfprojects.org list.
2. Notice popup modal with no information
3. Click the X to close and notice the page results in a server error as no alias is included in the return url. (shown below)

## Screenshots

![image](https://github.com/oqtane/oqtane.framework/assets/13577556/8b172ad1-ed7e-404a-a798-216b5013de73)
![image](https://github.com/oqtane/oqtane.framework/assets/13577556/c06189ef-4816-45b4-b356-98b21ee2541a)

**Comment by sbwalker** [comment]
@thabaum thank you for reporting... this turned out to be an issue in 5.1. The problem is resolved and has be deployed to the site https://dnfprojects.org

**Comment by thabaum** [comment]
@sbwalker works great.  Thanks.
