### ISSUE TITLE
Bug: Chart Stats are not being displayed in the line chart.

### ISSUE THREAD

**Issue by thabaum** [oqtane/DNF.Projects#9]
# Issue

## Description

Stats not displayed properly with the line chart.

## Steps to Reproduce

1.  Click on the magnifying glass icon to view stat details
2.  Notice the lines are flat and not representing the data presented.

## Screenshot

![image](https://github.com/oqtane/DNF.Projects/assets/13577556/e8818a26-da0d-480b-9db0-ee0fd05098aa)

**Comment by sbwalker** [comment]
@thabaum the graph is correct... the problem is the scale of the various metrics... and the fact that the trend lines increase very gradually. 

![image](https://github.com/oqtane/DNF.Projects/assets/4840590/261733ac-183e-4fdf-9efd-f514bf10dafe)

**Comment by thabaum** [comment]
You are correct.  

If you select a time frame it should probably change the graph similar to how it does it in GitHub for contributors commits.  Might have to change the range from 0 to 100 for example to graph from 80-100 to see there is activity.

**Comment by thabaum** [comment]
@sbwalker I now see it looks OK when you select just the one category.

**Comment by thabaum** [comment]
maybe the default can be the default metric used on the home page.

**Comment by sbwalker** [comment]
the current module is only intended to be an example and it is serving the needs of https://dnfprojects.com so I do not intend to add enhancements to this project at this time.

**Comment by thabaum** [comment]
Sounds good.  It works as is, I do notice the pager could be enhanced in Oqtane Framework to show the other pages to click on.

I will maybe put an enhancement request down the road for this once so if you have 2 -5 pages or so they show up as links you can click on or hit the arrow icon.  For now focus on stabilizing 5.1.

So it works more like this:
![image](https://github.com/oqtane/DNF.Projects/assets/13577556/d01e9521-668d-4af3-bfd3-0dff8fec5975)

Instead of this:
![image](https://github.com/oqtane/DNF.Projects/assets/13577556/30ad9ed2-63c1-43c5-a5e8-6907483d5092)

This is just some feedback other than that as the chart does work so there isn't any kind of real fire to put out.

**Comment by sbwalker** [comment]
@thabaum the Pager component already supports the ability to display pages which can be clicked. The DNF.Projects module is configured to only show the current page because it is optimized for mobile viewing - where the horizontal screen real estate is limited. If you look at the any of the Admin screens in Oqtane you will see they display 3 clickable pages by default.
